--GoT Tenant Info
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('Ned Stark', 'got');
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('Jamie Lannister', 'got');
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('Daenerys Targaryen', 'got');

--Seinfeld Tenant Info
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('Jerry Seinfeld', 'seinfeld');
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('George Costanza', 'seinfeld');
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('Elaine Benes', 'seinfeld');
INSERT INTO CHARACTER(NAME, TENANT_ID) VALUES('Kramer', 'seinfeld');